---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = ""
)
```

# AIxR


A repository as a [discussion place](https://github.com/teunbrand/ggplot-extension-club/discussions) for extending the ggplot2 R package. 


This repository will accommodate some discussion outside The AIxR meetings and coordination efforts.  Feel free to participate in discussions and be in touch!


Meetings:


```{r, echo = F, results = 'asis'}
tibble::tribble(~ date, ~ presenter, ~ package, ~`special topic`, #~link,
"2025-10-29","Kyle Walker", "", "spatial",
"Tentative Nov/Dec", "Frank Hull", "ggpal", "AI x coded viz") ->
meetings


t <- tempfile()
readr::write_csv(meetings, t)
readr::write_csv(meetings, "meetings.csv")

library(magrittr)
readLines(t) %>% 
  .[2:length(.)] %>% 
  paste("- ", ., "\n\n") %>% 
  stringr::str_replace_all(",", ", ") %>% 
  stringr::str_remove_all(", NA") %>% 
  cat()

# meetings |>
#   gt::gt() |>
#   gt::fmt_date(columns = date, date_style = "m_day_year")

# logo_str <- "raw/main/man/figures/logo.png"
# 
# # https://github.com/CHOP-CGTInformatics/ggswim/raw/main/man/figures/logo.png
# library(tidyverse)
# meetings %>% 
#   mutate(package_url = str_extract(package, "\\(.+\\)") %>% 
#            str_remove_all("\\(|\\)")) %>% 
#   mutate(logo_url = paste0(package_url, logo_str)) ->
#   meetings_w_logos
# 
# meetings_w_logos$logo_url
```



<!-- -   [{animint2}](https://github.com/animint/animint2), Toby Hocking, August 19, 2024 -->
<!-- Past meetings -->

<!-- -   [{ggnewscale}](https://eliocamp.github.io/ggnewscale/), Elio Campitelli, June 22/23, 2024 -->

<!-- -   [{ggedit}](https://yonicd.github.io/ggedit/), Jonathan Sidi, May 11, 2024 -->

<!-- -   A conversation with Di Cook, early extension and [{GGally}](https://ggobi.github.io/ggally/), March 12/13, 2024 -->

<!-- -   [{ggdag}](https://r-causal.github.io/ggdag/), Malcolm Barrett, Feb 10, 2024 -->

<!-- -   [{ggflowchart}](https://nrennie.rbind.io/ggflowchart/) Nicola Rennie & [{arrowheadr}](https://wjschne.github.io/arrowheadr/) W. Joel Schneider Nov 4, 2023 -->

<!-- -   [{ggeasy}](https://jonocarroll.github.io/ggeasy/) Jonathan Carroll, Sept 2, 2023 -->

<!-- -   [{ggsurvfit}](https://www.danieldsjoberg.com/ggsurvfit/), Daniel Sjoberg, June 10, 2023 -->

<!-- -   [{ggcirclepack}](https://github.com/EvaMaeRey/ggcirclepack), Gina Reynolds, April 15, 2023 -->

<!-- -   [*Fundamentals of Data Visualization*](), Claus Wilke, Jan 28, 2023 -->

<!-- -   [{ggtrace}](https://yjunechoe.github.io/ggtrace/), June Choe, July 16, 2022 -->

<!-- -   [{ggh4x}](https://teunbrand.github.io/ggh4x/), Teun Van Den Brand, June 11, 2022 -->

<!-- -   [{geomtextpath}](https://allancameron.github.io/geomtextpath/) Allan Cameron May 7, 2022 -->

<!-- -   [{ggbump}](https://github.com/davidsjoberg/ggbump) David Sjoberg, April 9, 2022 -->


<!-- ## Other Resources -->

```{r, results = 'asis', echo = F}
unaffiliated_resources <- '
**General**

* The [ggplot2](https://github.com/tidyverse/ggplot2) repository

**Extending ggplot2**

* The extending ggplot2 chapters of the [ggplot2 book](https://ggplot2-book.org/):
  * Chapter 19: [Programming with ggplot2](https://ggplot2-book.org/programming.html)
  * Chapter 20: [ggplot2 internals](https://ggplot2-book.org/internals.html)
  * Chapter 21: [Writing ggplot2 extensions](https://ggplot2-book.org/extensions.html)
  * Chapter 22: [Case Study: Springs](https://ggplot2-book.org/spring1.html)
* The [extending ggplot2](https://ggplot2.tidyverse.org/articles/extending-ggplot2.html) vignette
* The [ggproto](https://stackoverflow.com/questions/tagged/ggproto) tag on StackOverflow

**Extensions**

* The [extensions gallery](https://exts.ggplot2.tidyverse.org/gallery/)
* The [Awesome `ggplot2`](https://github.com/erikgahner/awesome-ggplot2) repository

**Talks**

* [Extending your ability to extend ggplot2](https://www.rstudio.com/resources/rstudioconf-2020/extending-your-ability-to-extend-ggplot2/) by Thomas Lin Pederson at rstudio::conf 2020

* [Best practises for programming with ggplot2](https://www.rstudio.com/resources/rstudioconf-2020/best-practices-for-programming-with-ggplot2/) by Dewey Dunnington at rstudio::conf 2020
* [Cracking open ggplot internals with {ggtrace}](https://www.rstudio.com/resources/rstudioconf-2020/best-practices-for-programming-with-ggplot2/) by June Choe at rstudio::conf 2022'

# cat(unaffiliated_resources)
writeLines(unaffiliated_resources, "unaffiliated_resources.txt")
```




